import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const adminEmail = "admin@demo.local";
  const adminPassword = "admin123";

  const ops = [
    { kind:"grant", titleRu:"Грант на исследование по климату", titleKz:"Климат бойынша зерттеу гранты", organization:"Global Science Fund", deadline:new Date("2026-06-30T00:00:00.000Z"), amount:15000, country:"Worldwide", field:"Environment", type:"Research Grant", descRu:"Поддержка исследований и пилотных проектов по адаптации к изменению климата. Финансирование покрывает полевые исследования, оборудование и публикацию результатов.", descKz:"Климаттың өзгеруіне бейімделу бойынша зерттеу және пилоттық жобаларды қолдау.", url:"https://globalscience.org/climate-grant" },
    { kind:"grant", titleRu:"AI for Health: грант на прототип", titleKz:"AI for Health: прототипке грант", organization:"HealthTech Alliance", deadline:new Date("2026-05-20T00:00:00.000Z"), amount:30000, country:"EU", field:"AI", type:"Research Grant", descRu:"Финансирование прототипов в области медицинского ИИ. Приоритет — диагностические системы и предиктивная аналитика для здравоохранения.", descKz:"Медициналық AI саласындағы прототиптерді қаржыландыру.", url:"https://healthtechalliance.eu/ai-grant" },
    { kind:"grant", titleRu:"Грант на развитие зелёной энергетики", titleKz:"Жасыл энергетиканы дамыту гранты", organization:"Clean Energy Foundation", deadline:new Date("2026-07-10T00:00:00.000Z"), amount:50000, country:"Worldwide", field:"Energy", type:"Project Grant", descRu:"Поддержка проектов по развитию возобновляемых источников энергии: солнечные панели, ветряные установки, накопители энергии.", descKz:"Жаңартылатын энергия көздерін дамыту жобаларын қолдау.", url:"https://cleanenergy.org/grant-2026" },
    { kind:"grant", titleRu:"Грант для социальных предпринимателей", titleKz:"Әлеуметтік кәсіпкерлер үшін грант", organization:"Social Impact Fund", deadline:new Date("2026-08-15T00:00:00.000Z"), amount:10000, country:"Kazakhstan", field:"Business", type:"Social Grant", descRu:"Финансирование проектов социального предпринимательства в Казахстане, направленных на решение актуальных общественных проблем.", descKz:"Қазақстанда өзекті қоғамдық мәселелерді шешуге бағытталған жобаларды қаржыландыру.", url:"https://socialimpact.kz/grant" },
    { kind:"grant", titleRu:"Грант на медицинские исследования ВОЗ", titleKz:"ДДҰ медициналық зерттеулерге гранты", organization:"WHO Research Fund", deadline:new Date("2026-06-20T00:00:00.000Z"), amount:75000, country:"Worldwide", field:"Medicine", type:"Research Grant", descRu:"ВОЗ поддерживает исследования в области инфекционных заболеваний и разработки вакцин в развивающихся странах.", descKz:"ДДҰ дамушы елдерде жұқпалы аурулар зерттеуін қолдайды.", url:"https://who.int/research-fund" },
    { kind:"grant", titleRu:"EU Horizon: грант для исследователей", titleKz:"EU Horizon: зерттеушілерге грант", organization:"European Commission", deadline:new Date("2026-10-31T00:00:00.000Z"), amount:150000, country:"EU", field:"Science", type:"Research Grant", descRu:"Программа Horizon Europe финансирует передовые научные исследования во всех областях знаний.", descKz:"Horizon Europe бағдарламасы барлық білім салаларындағы ғылыми зерттеулерді қаржыландырады.", url:"https://ec.europa.eu/horizon" },
    { kind:"grant", titleRu:"Грант на кибербезопасность", titleKz:"Киберқауіпсіздік гранты", organization:"CyberDefense Institute", deadline:new Date("2026-09-01T00:00:00.000Z"), amount:20000, country:"USA", field:"IT", type:"Research Grant", descRu:"Гранты для университетов на разработку учебных программ по кибербезопасности. Приоритет — практические лаборатории и CTF.", descKz:"Университеттерге киберқауіпсіздік оқу бағдарламаларын жасауға арналған гранттар.", url:"https://cyberdefense.edu/grants" },
    { kind:"grant", titleRu:"Программа Болашакер: ИТ-гранты", titleKz:"Болашакер бағдарламасы: АТ-гранттар", organization:"Qaztech Ventures", deadline:new Date("2026-08-31T00:00:00.000Z"), amount:20000, country:"Kazakhstan", field:"IT", type:"Program", descRu:"Поддержка казахстанских разработчиков и стартапов. Включает менторство и грант на разработку MVP.", descKz:"Қазақстандық әзірлеушілер мен стартаптарды қолдау бағдарламасы.", url:"https://qaztech.kz/bolashaker" },
    { kind:"grant", titleRu:"Women in Tech Grant", titleKz:"Технологиялардағы әйелдер гранты", organization:"UN Women / UNDP", deadline:new Date("2026-06-15T00:00:00.000Z"), amount:12000, country:"Central Asia", field:"IT", type:"Social Grant", descRu:"Гранты для создания IT-проектов и стартапов, основанных женщинами в Центральной Азии.", descKz:"Орталық Азияның технологиялық секторындағы әйелдерді қолдау бағдарламасы.", url:"https://unwomen.org/tech-grant-ca" },
    { kind:"grant", titleRu:"Microsoft для некоммерческих организаций", titleKz:"Microsoft коммерциялық емес ұйымдар үшін", organization:"Microsoft Philanthropies", deadline:new Date("2026-12-31T00:00:00.000Z"), amount:5000, country:"Worldwide", field:"IT", type:"Technology Grant", descRu:"Microsoft предоставляет НКО лицензии на ПО, облачные ресурсы Azure и финансирование для социально значимых проектов.", descKz:"Microsoft НҚҰ-ларға Azure бұлтты ресурстарын және қаржыландыруды береді.", url:"https://microsoft.com/en-us/nonprofits" },
    { kind:"scholarship", titleRu:"Стипендия для магистратуры STEM", titleKz:"STEM магистратурасына стипендия", organization:"Open Education Trust", deadline:new Date("2026-07-15T00:00:00.000Z"), amount:8000, country:"Kazakhstan", field:"STEM", type:"Scholarship", degree:"Master", descRu:"Стипендия для обучения на магистратуре в приоритетных STEM-направлениях. Покрывает обучение и ежемесячное пособие.", descKz:"Басым STEM бағыттары бойынша магистратурада оқуға арналған стипендия.", url:"https://openeducation.kz/stem-scholarship" },
    { kind:"scholarship", titleRu:"PhD Fellowship: Data Science", titleKz:"PhD Fellowship: Data Science", organization:"Nordic Research School", deadline:new Date("2026-05-05T00:00:00.000Z"), amount:12000, country:"Norway", field:"Data Science", type:"Fellowship", degree:"PhD", descRu:"Финансирование и менторство для PhD в области Data Science. Включает участие в конференциях и публикацию в международных журналах.", descKz:"Data Science саласындағы PhD үшін қаржыландыру және менторлық.", url:"https://nordicresearch.no/phd-fellowship" },
    { kind:"scholarship", titleRu:"Стипендия Chevening для казахстанцев", titleKz:"Қазақстандықтарға Chevening стипендиясы", organization:"UK Government / FCO", deadline:new Date("2026-11-04T00:00:00.000Z"), amount:25000, country:"UK", field:"Any Field", type:"Full Scholarship", degree:"Master", descRu:"Полностью финансируемая программа магистратуры в Великобритании для лидеров из Казахстана. Включает обучение, проживание и авиабилеты.", descKz:"Қазақстандық көшбасшылар үшін Ұлыбританиядағы толығымен қаржыландырылатын магистратура.", url:"https://chevening.org/scholarship/kazakhstan" },
    { kind:"scholarship", titleRu:"Болашақ: стипендия Президента РК", titleKz:"Болашақ: ҚР Президентінің стипендиясы", organization:"JSC Center for International Programs", deadline:new Date("2026-12-01T00:00:00.000Z"), amount:35000, country:"Worldwide", field:"Any Field", type:"Full Scholarship", degree:"Master", descRu:"Программа «Болашақ» финансирует обучение граждан Казахстана в ведущих зарубежных университетах мира.", descKz:"«Болашақ» бағдарламасы Қазақстан азаматтарының шетелдік университеттерде оқуын қаржыландырады.", url:"https://bolashak.gov.kz" },
    { kind:"scholarship", titleRu:"DAAD: стипендия для аспирантов", titleKz:"DAAD: аспиранттарға стипендия", organization:"DAAD Germany", deadline:new Date("2026-10-15T00:00:00.000Z"), amount:18000, country:"Germany", field:"Engineering", type:"Full Scholarship", degree:"PhD", descRu:"DAAD финансирует обучение иностранных аспирантов в Германии. Включает языковые курсы, страховку и ежемесячную стипендию.", descKz:"DAAD Германияда шетелдік аспиранттарды оқытуды қаржыландырады.", url:"https://daad.de/en/scholarships" },
    { kind:"scholarship", titleRu:"Erasmus+: студенческий обмен", titleKz:"Erasmus+: студенттік алмасу", organization:"European Union", deadline:new Date("2026-03-31T00:00:00.000Z"), amount:6000, country:"EU", field:"Any Field", type:"Exchange Program", degree:"Bachelor", descRu:"Erasmus+ поддерживает студенческий обмен между университетами Европы. Гранты на период от 3 месяцев до 1 года.", descKz:"Erasmus+ Еуропа университеттері арасындағы студенттік алмасуды қолдайды.", url:"https://erasmus-plus.ec.europa.eu" },
    { kind:"scholarship", titleRu:"Fulbright: США для исследователей", titleKz:"Fulbright: зерттеушілер үшін АҚШ", organization:"US Department of State", deadline:new Date("2026-09-20T00:00:00.000Z"), amount:40000, country:"USA", field:"Any Field", type:"Full Scholarship", degree:"PhD", descRu:"Программа Fulbright — гранты иностранным исследователям для работы и учёбы в США. Покрывает проживание и обучение.", descKz:"Fulbright бағдарламасы шетелдік зерттеушілерге АҚШ-та жұмыс істеуге грант береді.", url:"https://fulbrightprogram.org" },
    { kind:"scholarship", titleRu:"Стипендия ООН для молодых лидеров", titleKz:"БҰҰ жас көшбасшыларға стипендиясы", organization:"United Nations", deadline:new Date("2026-09-30T00:00:00.000Z"), amount:22000, country:"Worldwide", field:"International Relations", type:"Fellowship", degree:"Master", descRu:"Стипендиальная программа ООН для молодых лидеров в области устойчивого развития, дипломатии и международного права.", descKz:"Тұрақты даму және дипломатия саласындағы жас көшбасшылар үшін БҰҰ бағдарламасы.", url:"https://un.org/young-leaders-scholarship" },
    { kind:"scholarship", titleRu:"Стипендия для бакалавров в США", titleKz:"АҚШ-та бакалавр үшін стипендия", organization:"American University System", deadline:new Date("2026-01-15T00:00:00.000Z"), amount:30000, country:"USA", field:"Any Field", type:"Full Scholarship", degree:"Bachelor", descRu:"Полностью финансируемая стипендия для поступления в американские университеты. Включает обучение, общежитие и питание.", descKz:"Американдық университеттерге түсуге арналған толықтай қаржыландырылатын стипендия.", url:"https://americanuniversity.edu/scholarships" },
    { kind:"competition", titleRu:"Startup Challenge 2026", titleKz:"Startup Challenge 2026", organization:"Innovation Hub", deadline:new Date("2026-06-05T00:00:00.000Z"), amount:50000, country:"Worldwide", field:"Startups", type:"Competition", organizer:"Innovation Hub", prize:50000, descRu:"Международный конкурс для стартапов с призом $50 000 и акселерацией. Принимаются заявки из всех стран.", descKz:"$50 000 жүлдесі бар халықаралық стартап байқауы.", url:"https://innovationhub.io/startup-challenge" },
    { kind:"competition", titleRu:"Хакатон AI для образования", titleKz:"Білім беруге арналған AI хакатоны", organization:"EdTech Foundation", deadline:new Date("2026-05-28T00:00:00.000Z"), amount:15000, country:"Kazakhstan", field:"AI", type:"Hackathon", organizer:"EdTech Foundation", prize:15000, descRu:"48-часовой хакатон по разработке AI-решений для образования. Команды до 5 человек. Первый приз — $15 000.", descKz:"Білім берудегі AI шешімдеріне арналған 48 сағаттық хакатон.", url:"https://edtech.kz/hackathon-2026" },
    { kind:"competition", titleRu:"GreenTech Awards 2026", titleKz:"GreenTech Awards 2026", organization:"Sustainable Future Network", deadline:new Date("2026-07-31T00:00:00.000Z"), amount:25000, country:"Europe", field:"Environment", type:"Award", organizer:"Sustainable Future Network", prize:25000, descRu:"Ежегодная премия для зелёных технологических стартапов. Победители получают инвестиции и место в акселераторе.", descKz:"Жасыл технологиялық стартаптар үшін жыл сайынғы сыйлық.", url:"https://greentechawards.eu" },
    { kind:"competition", titleRu:"FinTech Innovation Cup", titleKz:"FinTech Innovation Cup", organization:"AIFC Fin Hub", deadline:new Date("2026-08-10T00:00:00.000Z"), amount:30000, country:"Kazakhstan", field:"Business", type:"Competition", organizer:"AIFC Fin Hub", prize:30000, descRu:"Конкурс для финтех-стартапов с призовым фондом $30 000 и возможностью пилота с казахстанскими банками.", descKz:"$30 000 жүлделік қоры бар финтех стартаптар байқауы.", url:"https://aifc.kz/fintechcup" },
    { kind:"competition", titleRu:"Google Solution Challenge 2026", titleKz:"Google Solution Challenge 2026", organization:"Google Developers", deadline:new Date("2026-03-28T00:00:00.000Z"), amount:10000, country:"Worldwide", field:"IT", type:"Competition", organizer:"Google Developers", prize:10000, descRu:"Глобальный конкурс Google для студентов — разработка решений для достижения ЦУР ООН.", descKz:"Студенттерге арналған Google-дің жаһандық байқауы.", url:"https://developers.google.com/gdsc-solution-challenge" },
    { kind:"competition", titleRu:"Национальная научная олимпиада РК", titleKz:"ҚР Ұлттық ғылым олимпиадасы", organization:"Ministry of Education RK", deadline:new Date("2026-04-30T00:00:00.000Z"), amount:5000, country:"Kazakhstan", field:"Science", type:"Olympiad", organizer:"Ministry of Education RK", prize:5000, descRu:"Ежегодная олимпиада по физике, химии и математике для студентов казахстанских вузов.", descKz:"Қазақстан жоғары оқу орындары студенттері үшін жыл сайынғы олимпиада.", url:"https://edu.gov.kz/olympiad" },
    { kind:"competition", titleRu:"NASA Space Apps Challenge", titleKz:"NASA Space Apps Challenge", organization:"NASA", deadline:new Date("2026-10-05T00:00:00.000Z"), amount:0, country:"Worldwide", field:"Science", type:"Hackathon", organizer:"NASA", prize:0, descRu:"Ежегодный хакатон NASA — 48 часов для решения задач, связанных с космосом и Землёй.", descKz:"NASA-ның жыл сайынғы халықаралық хакатоны — ғарыш міндеттерін шешуге 48 сағат.", url:"https://spaceappschallenge.org" },
    { kind:"competition", titleRu:"ICPC: олимпиада по программированию", titleKz:"ICPC: бағдарламалау олимпиадасы", organization:"ICPC Foundation", deadline:new Date("2026-11-15T00:00:00.000Z"), amount:8000, country:"Worldwide", field:"IT", type:"Olympiad", organizer:"ICPC Foundation", prize:8000, descRu:"Крупнейший в мире конкурс по программированию для студентов. Команды из 3 человек решают алгоритмические задачи.", descKz:"Студенттерге арналған бағдарламалаудың әлемдегі ең ірі байқауы.", url:"https://icpc.global" },
  ];

  await prisma.favorite.deleteMany();
  await prisma.user.deleteMany();
  await prisma.opportunity.deleteMany();
  await prisma.opportunity.createMany({ data: ops });

  const passwordHash = await bcrypt.hash(adminPassword, 10);
  await prisma.user.create({
    data: { email: adminEmail, name: "Admin", passwordHash, role: "ADMIN" },
  });

  console.log("Seeded " + ops.length + " opportunities.");
}

main()
  .then(async () => { await prisma.$disconnect(); })
  .catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exit(1); });
